server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=/identity-svc/api/v1/auth/**
            - Path=/identity-svc/api/v1/forgotPassword/**
            - Path=/identity-svc/api/v1/userManagement/**
          filters:
            - StripPrefix=1
        - id: warehouse-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/warehouse-svc/**
          filters:
            - StripPrefix=2
